export const teaTypes = [
  {
    list: "tea",
    title: "Classic",
    types: [
      "Assam Gold - Black",
      "Bollywood Chai - Black",
      "Chineese Sencha - Green",
      "Bai Mu Dan - White",
      "Divine Elixir - White",
      "Spiced Pie - Pu-erh",
    ],
  },
  {
    list: "tea",
    title: "Flavoured",
    types: ["Earl Grey - Black", "Jasmine - Green", "Masala - Black"],
  },
  {
    list: "tea",
    title: "Infusions",
    types: ["Yerba Mate"],
  },
];

export const teaProducts = [
  {
    productId: 11,
    list: "tea",
    title: "Assam Gold",
    type: "Black",
    quantity: 80,
    price: 9.99,
    category: "classic",
  },
  {
    productId: 12,
    list: "tea",
    title: "Bollywood Chai",
    type: "Black",
    quantity: 80,
    price: 6.99,
    category: "classic",
  },
  {
    productId: 13,
    list: "tea",
    title: "Chinese Sencha",
    type: "Green",
    quantity: 80,
    price: 12.99,
    category: "classic",
  },
  {
    productId: 14,
    list: "tea",
    title: "Bai Mu Dan",
    type: "White",
    quantity: 60,
    price: 14.99,
    category: "classic",
  },
  {
    productId: 15,
    list: "tea",
    title: "Divine Elixir",
    type: "White",
    quantity: 20,
    price: 11.99,
    category: "classic",
  },
  {
    productId: 16,
    list: "tea",
    title: "Spiced Pie",
    type: "Pu-erh",
    quantity: 120,
    price: 3.99,
    category: "classic",
  },
  {
    productId: 17,
    list: "tea",
    title: "Earl Grey",
    type: "Black",
    quantity: 60,
    price: 18.99,
    category: "flavoured",
  },
  {
    productId: 18,
    list: "tea",
    title: "Jasmine",
    type: "Green",
    quantity: 20,
    price: 29.99,
    category: "flavoured",
  },
  {
    productId: 19,
    list: "tea",
    title: "Masala",
    type: "Black",
    quantity: 120,
    price: 12.99,
    category: "flavoured",
  },
  {
    productId: 20,
    list: "tea",
    title: "Yerba Mate",
    type: "Black",
    quantity: 300,
    price: 3.99,
    category: "infusions",
  },
];

export const coffeeTypes = [
  {
    list: "coffee",
    title: "Arabica",
    types: [
      "Blue mountain - Japan",
      "Medellin excelso - Colombia",
      "Arabica santos - Brasil",
      "Arabica mokka - Ethiopia",
      "Arabica tokke - Nicaragua",
    ],
  },
  {
    list: "coffee",
    title: "Robusta",
    types: [
      "Robusta santos - Brasil",
      "Robusta koffa- Cameroon",
      "Robusta losano - Kenya",
    ],
  },
  {
    list: "coffee",
    title: "Mix",
    types: ["Robusta 30% Arabica 70%", "Robusta 20% Arabica 80%"],
  },
];

export const coffeeProducts = [
  {
    productId: 1,
    list: "coffee",
    title: "Mountain",
    type: "Japan",
    quantity: 120,
    price: 1.99,
    category: "Arabica",
  },
  {
    productId: 2,
    list: "coffee",
    title: "Excelso",
    type: "Colombia",
    quantity: 160,
    price: 9.99,
    category: "Arabica",
  },
  {
    productId: 3,
    list: "coffee",
    title: "Santos",
    type: "Brasil",
    quantity: 280,
    price: 12.99,
    category: "Arabica",
  },
  {
    productId: 4,
    list: "coffee",
    title: "Mokka",
    type: "Ethiopia",
    quantity: 300,
    price: 12.99,
    category: "Arabica",
  },
  {
    productId: 5,
    list: "coffee",
    title: "Tokke",
    type: "Nicaragua",
    quantity: 200,
    price: 2.99,
    category: "Arabica",
  },
  {
    productId: 6,
    list: "coffee",
    title: "Santos",
    type: "Brasil",
    quantity: 820,
    price: 32.99,
    category: "Robusta",
  },
  {
    productId: 7,
    list: "coffee",
    title: "Koffa",
    type: "Cameroon",
    quantity: 800,
    price: 12.99,
    category: "Robusta",
  },
  {
    productId: 8,
    list: "coffee",
    title: "Losano",
    type: "Kenya",
    quantity: 100,
    price: 9.99,
    category: "Robusta",
  },
  {
    productId: 9,
    list: "coffee",
    title: "30% 70%",
    type: "Robusta Arabica",
    quantity: 520,
    price: 18.99,
    category: "Mix",
  },
  {
    productId: 10,
    list: "coffee",
    title: "20% 80%",
    type: "Robusta Arabica",
    quantity: 100,
    price: 10.99,
    category: "Mix",
  },
];
